spring.application.name=Homey_Bites

#MongoDB
spring.mongodb.uri=mongodb://localhost:27017/Homey


#AWS S3 config
aws.access.key=${AWS_ACCESS_KEY}
aws.secret.key=${AWS_SECRET_KEY}
aws.region=us-east-1
aws.s3.bucketname=foodis-bit

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

jwt.secret.key=ddsfvzxvhfjfhuiOFAUHFEJIRRNUIYIUHIIWGIGPFIGPIFG==

#Razorpayment confir
razorpay_key=${RAZORPAY_KEY}
razorpay_secret=${RAZORPAY_SECRET}
